# Generated by Django 5.2.3 on 2025-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start", models.TimeField(help_text="Start time of the slot (HH:MM)")),
                ("stop", models.TimeField(help_text="End time of the slot (HH:MM)")),
                (
                    "camera_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of camera IDs associated with this time slot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "indexes": [
                    models.Index(
                        fields=["day", "start"], name="schedule_ti_day_bf5226_idx"
                    ),
                    models.Index(
                        fields=["day", "stop"], name="schedule_ti_day_c6cde3_idx"
                    ),
                ],
            },
        ),
    ]
